name: s3-deploy-wp-refarch
on: [push]
# on:
#   pull_request:
#     branches:
#       - master
#     types: [opened, synchronize, closed]

jobs:
  SyncResources:
    name: Upload template files
    #if: github.event.pull_request.merged == true 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Configure AWS credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: S3 sync
        env:
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
        run: aws s3 sync . s3://$S3_BUCKET/refarch-wordpress/ --delete --exclude "images/*"
